services:
  caddy:
    container_name: caddy
    image: caddy:2.10.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
    depends_on:
      - frontend
      - backend
    networks:
      - caddy

  frontend:
    container_name: frontend
    image: public.ecr.aws/y1i2z7p3/csci4650-final/frontend:latest
    restart: unless-stopped
    networks:
      - caddy

  backend:
    container_name: backend
    image: public.ecr.aws/y1i2z7p3/csci4650-final/backend:latest
    restart: unless-stopped
    environment:
      DB_CONNECTION_URI: ${DB_CONNECTION_URI}
    networks:
      - caddy

networks:
  caddy:
    name: caddy

volumes:
  mysql_data:
    name: final_project_mysql_data
  caddy_data:
    name: final_project_caddy_data

