services:
  frontend:
    container_name: frontend
    build:
      context: grocery-frotend
    restart: unless-stopped
    ports:
      - "80:4200"
    environment:
      API_URL: ${BACKEND_API_URL}
    networks:
      - front

  backend:
    container_name: backend
    build:
      context: backend
    restart: unless-stopped
    environment:
      DB_CONNECTION_URI: ${DB_CONNECTION_URI}
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - front
      - back

  mysql_db:
    image: mysql:8.0 # You can specify a different version if needed
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS} # Replace with a strong password
      MYSQL_DATABASE: ${DB_DATABASE} # Optional: create a database on startup
      MYSQL_USER: ${DB_USER} # Optional: create a user
      MYSQL_PASSWORD: ${DB_PASS} # Optional: password for the user
    volumes:
      - mysql_data:/var/lib/mysql # Persist data in a named volume
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u "$${DB_USER}" --password="$${DB_PASS}" --silent']
      interval: 3s
      retries: 5
      start_period: 30s # Restart the container if it stops
    networks:
      - back

networks:
  front:
    name: front
  back:
    name: back

volumes:
  mysql_data: # Define the named volume

