services:
  caddy:
    container_name: caddy
    image: caddy:2.10.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
    depends_on:
      - frontend
      - backend
    networks:
      - caddy

  frontend:
    container_name: frontend
    image: 921075274644.dkr.ecr.us-east-1.amazonaws.com/csci4650-final/frontend:latest
    restart: unless-stopped
    networks:
      - caddy

  backend:
    container_name: backend
    image: 921075274644.dkr.ecr.us-east-1.amazonaws.com/csci4650-final/backend:latest
    restart: unless-stopped
    environment:
      DB_CONNECTION_URI: ${DB_CONNECTION_URI}
    networks:
      - caddy
      - database

networks:
  caddy:
    name: caddy
  database:
    name: database

volumes:
  mysql_data:
    name: final_project_mysql_data
  caddy_data:
    name: final_project_caddy_data

